# Generated by Django 5.0.2 on 2024-02-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_options_productimage_alt_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(help_text='Required', max_length=255, verbose_name='title'),
        ),
    ]
